.\" Copyright (c) 2012, John Mehr <jcm@visi.com>
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\" $FreeBSD$
.\"
.Dd December 30, 2012
.Dt SVNUP
.Os
.Sh NAME
.Nm svnup
.Nd A lightweight, dependency-free program to pull source from an Apache Subversion server.
.Sh SYNOPSIS
.Nm
.Cm section
.Op Fl 46fntV
.Op Fl b Ar branch
.Op Fl h Ar hostname/address
.Op Fl k Ar known files directory
.Op Fl l Ar local directory
.Op Fl o Ar port
.Op Fl p Ar protocol
.Op Fl r Ar revision
.Op Fl v Ar verbosity
.Sh DESCRIPTION
.Nm
is a minimalist program used to create or synchronize a local copy of a Subversion repository.  It is not intended to be a full-featured replacement for the devel/subversion port, but rather, is intended to provide a convenient way for users to update FreeBSD source files without having to install devel/subversion and all of its related dependencies.
.Sh OPTIONS
Configuration options are stored in /usr/local/etc/svnup.conf and are grouped into commonly used sections (additional custom sections can be added to this file).  The following command line options can be used to override the default and/or section values:
.Bl -tag -width Fl
.It Fl 4
Use IPv4 addresses only.
.It Fl 6
Use IPv6 addresses only.
.It Fl b
The Subversion branch to retrieve.
.It Fl f
Display all files found in the target directory structure that are not present in the repository (each file is displayed with a leading "*").
.It Fl h
The hostname or IP address of the Subversion repository.
.It Fl k
The local directory to save the lists of known files to.
.It Fl l
The local directory to save the repository's files to.
.It Fl n
Display the last known revision number for the specified section and exit.
.It Fl o
The custom port number on the server to connect to.
.It Fl p
The protocol used to connect to the server (currently supported protocols are svn, http and https).
.It Fl r
The revision number to retrieve (defaults to the branch's most recent revision if this option is not specified). 
.It Fl t
Remove all files in the local directory tree that do not exist in the repository.  This will result in an exact match of the contents of the remote repository and will remove files in directories like /usr/ports/distfiles, /usr/src/sys/amd64/conf/, etc.  Proceed with caution.
.It Fl v
How verbose the output should be (0 = no output, 1 = show only names of the updated files/folders, 2 = also show a progress indicator, 3 = also show commands sent to the server and show svn response codes -- useful when debugging).
.It Fl V
Display the version number and exit.
.El
.Sh FILES
.Bl -tag -width "/usr/local/etc/svnup.conf"
.It /usr/local/etc/svnup.conf
Default location of the
.Nm
configuration file.
.It /var/tmp/svnup
Default location where
.Nm
stores its lists of known files.  The files stored here are used during subsequent runs to determine which files have been removed from the repository and are safe to delete locally.
.El
.Sh DIAGNOSTICS
Because
.Nm
doesn't use the .svn folder that Subversion's svn client uses, you may experience difficulties using svn after using svnup in a given directory tree.
.Sh EXAMPLES
Using the configuration options for commonly used branches stored in /usr/local/etc/svnup.conf, to retrieve/checkout a copy of the most recent revision of the stable/9 branch:
.Pp
.Dl "svnup stable"
.Pp
To retrieve a copy of the most recent stable/9 branch, but store it in /tmp/stable (without modifying /usr/local/etc/svnup.conf)
.Pp
.Dl "svnup stable -l /tmp/stable"
.Sh SEE ALSO
.Xr svnup.conf 5
.Sh AUTHORS
John Mehr <jmehr@umn.edu> is the author of
.Nm
and this man page.
